module.exports.PREFIX = {
    DISCOVERY: 'discovery',
    SERVICES: 'services',
    JOBS: 'jobs',
    STATE: 'state',
    TASKS: 'tasks',
    WORKERS: 'workers',
    DRIVERS: 'drivers',
    JOB_RESULTS: 'jobResults',
    JOB_STATUS: 'jobStatus',
    WEBHOOKS: 'webhooks',
    PIPELINES: 'pipelines',
    EXECUTIONS: 'executions',
    RUNNING_PIPELINES: 'runningPipelines',
    ALGORITHM_QUEUE: 'algorithmQueue',
    RESOURCE_REQUIREMENTS: 'algorithmRequirements',
    ALGORITHM_EXECUTIONS: 'algorithmExecutions',
    TEMPLATE_STORE: 'algorithmTemplates',
    PIPELINE_DRIVER_TEMPLATE: 'pipelineDriverTemplates',
    PIPELINE_DRIVER_QUEUE: 'pipelineDriverQueue',
    PIPELINE_DRIVER_REQUIREMENTS: 'pipelineDriverRequirements',
    ALGORITHM_DEBUG: 'debug/algorithm'
};
